// tui-agent/src/components/panels/ToolPanel.tsx
import React from 'react';
import { useColors } from '../../theme/index.js';
import { Collapsible, Badge, Spinner } from '../shared/index.js';

export interface ToolExecution {
  id: string;
  name: string;
  category: string;
  status: 'pending' | 'awaiting_approval' | 'running' | 'completed' | 'error';
  args?: Record<string, unknown>;
  result?: string;
  error?: string;
  startedAt: number;
  completedAt?: number;
}

export interface ToolPanelProps {
  /** Whether the panel is expanded */
  isOpen: boolean;
  /** Toggle callback */
  onToggle: () => void;
  /** Recent tool executions */
  tools: ToolExecution[];
  /** Currently pending approval */
  pendingApproval?: ToolExecution;
  /** Callback for approval */
  onApprove?: (toolId: string) => void;
  /** Callback for rejection */
  onReject?: (toolId: string) => void;
}

export function ToolPanel({
  isOpen,
  onToggle,
  tools,
  pendingApproval,
  onApprove,
  onReject,
}: ToolPanelProps) {
  const colors = useColors();

  const statusColors: Record<ToolExecution['status'], string> = {
    pending: colors.fg.tertiary,
    awaiting_approval: colors.semantic.warning,
    running: colors.agent.executing,
    completed: colors.semantic.success,
    error: colors.semantic.error,
  };

  const runningCount = tools.filter(t => t.status === 'running').length;

  return (
    <Collapsible
      title="Tools"
      isOpen={isOpen}
      onToggle={onToggle}
      shortcut="o"
      badge={
        runningCount > 0 ? (
          <box flexDirection="row" gap={1}>
            <Spinner />
            <Badge variant="info">{String(runningCount)}</Badge>
          </box>
        ) : tools.length > 0 ? (
          <Badge variant="default">{String(tools.length)}</Badge>
        ) : undefined
      }
    >
      {/* Pending Approval Alert */}
      {pendingApproval && (
        <box
          flexDirection="column"
          padding={1}
          backgroundColor={colors.bg.elevated}
          border
          borderStyle="double"
          borderColor={colors.semantic.warning}
          style={{ marginBottom: 2 }}
        >
          <box flexDirection="row" gap={1}>
            <text style={{ fg: colors.semantic.warning }}>⚠</text>
            <text style={{ fg: colors.fg.primary }}>Approval Required</text>
          </box>
          <text style={{ fg: colors.fg.secondary }}>{pendingApproval.name}</text>
          <text style={{ fg: colors.fg.tertiary }}>
            {JSON.stringify(pendingApproval.args, null, 2).slice(0, 100)}
          </text>
          <box flexDirection="row" gap={2} style={{ marginTop: 1 }}>
            <text style={{ fg: colors.semantic.success }}>[y] Approve</text>
            <text style={{ fg: colors.semantic.error }}>[n] Reject</text>
          </box>
        </box>
      )}

      {/* Tool History */}
      {tools.length > 0 ? (
        <scrollbox
          style={{
            maxHeight: 10,
            backgroundColor: colors.bg.tertiary,
          }}
        >
          {tools.map((tool) => (
            <box
              key={tool.id}
              flexDirection="row"
              gap={1}
              style={{ marginBottom: 1 }}
            >
              <text style={{ fg: statusColors[tool.status] }}>
                {tool.status === 'running' ? '●' :
                 tool.status === 'completed' ? '✓' :
                 tool.status === 'error' ? '✗' :
                 tool.status === 'awaiting_approval' ? '?' :
                 '○'}
              </text>
              <text style={{ fg: colors.fg.secondary }}>{tool.name}</text>
              {tool.status === 'running' && <Spinner />}
              {tool.completedAt && (
                <text style={{ fg: colors.fg.tertiary }}>
                  {`${tool.completedAt - tool.startedAt}ms`}
                </text>
              )}
            </box>
          ))}
        </scrollbox>
      ) : (
        <text style={{ fg: colors.fg.tertiary }}>No tool executions</text>
      )}
    </Collapsible>
  );
}

// oci-ai-chat/src/lib/components/panels/ToolPanel.svelte
<script lang="ts">
  import { Collapsible, Spinner, Badge } from '$lib/components/ui/index.js';
  import type { ToolCall } from '$lib/tools/types.js';

  interface Props {
    isOpen?: boolean;
    tools?: ToolCall[];
    pendingApproval?: ToolCall;
    ontoggle?: () => void;
    onapprove?: (toolId: string) => void;
    onreject?: (toolId: string) => void;
  }

  let {
    isOpen = false,
    tools = [],
    pendingApproval,
    ontoggle,
    onapprove,
    onreject,
  }: Props = $props();

  const runningCount = $derived(tools.filter((t) => t.status === 'running' || t.status === 'streaming').length);

  const statusColors: Record<string, string> = {
    pending: 'text-tertiary',
    awaiting_approval: 'text-warning',
    running: 'text-executing',
    streaming: 'text-streaming',
    completed: 'text-success',
    error: 'text-error',
  };

  const statusIcons: Record<string, string> = {
    pending: '○',
    awaiting_approval: '?',
    running: '●',
    streaming: '◐',
    completed: '✓',
    error: '✗',
  };

  function isDanger(toolName: string): boolean {
    const name = toolName.toLowerCase();
    return name.startsWith('delete') || name.startsWith('terminate') || name.startsWith('stop');
  }
</script>

<Collapsible title="Tools" {isOpen} shortcut="o" {ontoggle}>
  {#snippet badge()}
    <div class="flex items-center gap-1">
      {#if runningCount > 0}
        <Spinner size="sm" />
        <Badge variant="info">{runningCount}</Badge>
      {:else if tools.filter(t => t.status === 'streaming').length > 0}
        <Spinner size="sm" variant="dots" />
        <Badge variant="accent">streaming</Badge>
      {:else if tools.length > 0}
        <Badge variant="default">{tools.length}</Badge>
      {/if}
    </div>
  {/snippet}

  <div class="space-y-3">
    <!-- Pending Approval Alert -->
    {#if pendingApproval}
      <div
        class="tool-approval animate-slide-in-up"
        class:danger={isDanger(pendingApproval.name)}
      >
        <div class="flex items-center gap-2 mb-2">
          <span class={isDanger(pendingApproval.name) ? 'text-error' : 'text-warning'}>
            {isDanger(pendingApproval.name) ? '⚠ DANGER' : '? Confirm'}
          </span>
          <Badge variant={isDanger(pendingApproval.name) ? 'error' : 'warning'}>
            Approval Required
          </Badge>
        </div>

        <p class="text-primary font-medium mb-2">{pendingApproval.name}</p>

        <div class="bg-tertiary p-2 rounded text-sm mb-3 max-h-32 overflow-y-auto">
          <p class="text-tertiary mb-1">Arguments:</p>
          {#each Object.entries(pendingApproval.args) as [key, value]}
            <div class="flex gap-2">
              <span class="text-secondary">{key}:</span>
              <span class="text-primary truncate">
                {typeof value === 'string' ? value : JSON.stringify(value)}
              </span>
            </div>
          {/each}
        </div>

        <div class="flex gap-3">
          <button
            class="btn btn-success text-sm"
            onclick={() => onapprove?.(pendingApproval.id)}
          >
            ✓ Approve (y)
          </button>
          <button
            class="btn btn-danger text-sm"
            onclick={() => onreject?.(pendingApproval.id)}
          >
            ✗ Reject (n)
          </button>
        </div>
      </div>
    {/if}

    <!-- Tool History -->
    <div class="max-h-40 overflow-y-auto space-y-1">
      {#if tools.length > 0}
        {#each tools as tool (tool.id)}
          <div class="flex items-center gap-2 text-sm">
            <span class={statusColors[tool.status]}>
              {#if tool.status === 'running'}
                <Spinner size="sm" />
              {:else}
                {statusIcons[tool.status]}
              {/if}
            </span>
            <span class="text-secondary">{tool.name}</span>
            {#if tool.completedAt && tool.startedAt}
              <span class="text-tertiary text-xs">
                {tool.completedAt - tool.startedAt}ms
              </span>
            {/if}
          </div>
        {/each}
      {:else if !pendingApproval}
        <p class="text-tertiary text-sm italic">No tool executions</p>
      {/if}
    </div>
  </div>
</Collapsible>
